### PR TITLE
Fix for flags handling

### PR DESCRIPTION
**Pull request by dariovillar**
With this little fix, flags are enabled and working resolving the  #1 issue. 

Tested with [this gist](https://gist.github.com/dariovillar/38f26294b5ebf7b899a4a30d3ab72648)

### CODE REVIEW

**Comment by tehnerd** [comment]
i will look into this on the weekend. thanks. but probably will fix my implementation instead of yours. mainly because i dont understand why netlink works in your case, because ip_vs's netlink interface expect flags to be binary types w/ size of 2*u32 (http://lxr.free-electrons.com/source/net/netfilter/ipvs/ip_vs_ctl.c#L2846)

**Comment by tehnerd** [comment]
i think in my implementantion i've fckedup order of bits (looking on http://lxr.free-electrons.com/source/include/uapi/linux/ip_vs.h#L288 i can see that i've put my values into mask field instead of flags)

**Comment by dariovillar** [comment]
Well, one thing to consider is the ability to OR flags, so byte array made things a little bit harder. However I'm glad this help you to realize how to fix it =) .

**Comment by tehnerd** [comment]
i've reimplemented this by myself w/ binary types (to honor IPVS'es netlink api). see comments in issue for examples etc

**Pull request closed without merging**
